mutations: data/pancan.merged.min3.hyper500.maf
data_dir: /projects/pancan_atlas/driver/data/
output_dir: /projects/pancan_atlas/driver/output/pancan_atlas_6_24_2016_hypermut500_min10/
trained_classifier: 2020plus.Rdata
NUMSIMULATIONS: 100000
NUMITER: 10
